controllers:
    resource: ../src/Controller/
    type: attribute

homepage:
    path: /
    controller: App\Controller\DialogController::defaultAction
troll_api_endpoint:
    path: /api/troll
    controller: App\Controller\DialogController::apiAction